Fixes widows error <<ImportError: cannot import name 'MidiEvaluator' from 'parser' [...]>>
Fixes the conflict name between standard library "parser" and "parser.py" by:
- Renaming parser.py to midi_parser.py in root of project.
- Updating tbon.py
Thanks to snippsat for his help.